title: Branum Stephan # your name (or website title) here
logo: "/images/Branum-profile pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Petroleum Engineer, Data Scientist, Southern Methodist University M.Sc. Data Science Fall 2021.  
  <br><br>
  Technology focused petroleum engineer with approximately 2 years of experience in working with upstream drilling data. Knowledgeable in drilling optimization through the use of SQL, Python, Spark SQL, Azure platforms, and more. 
  Future skills include: R, Java, Sci-kit Learn
  <br><br>
  <a href="https://www.linkedin.com/in/m-branum-stephan-84b26aa0/">View My LinkedIn Profile</a> 
  <br>
  <a href = "mailto:branum.stephan@gmail.com">branum.stephan@gmail.com</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
