title: Branum Stephan # your name (or website title) here
logo: "/images/Branum-profile pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Petroleum Engineer, Data Scientist | Southern Methodist University M.Sc. Data Science Fall 2021.  
  <br><br>
  <b>About</b>
  Technology focused petroleum engineer with 2+ years of experience in working with upstream drilling data. Knowledgeable in drilling optimization through the use of SQL, Python, R, Spark SQL, Cloud Computing (Azure), and more. 
  <br><br>
  Currently employed at <a href="https://www.corva.ai">Corva AI</a> as a Data Quality Specialist, creating unstructured data pipelines for QC Dashboards. Additionally, I have created automation through the use of external API to provide integration between our operations department and internal tools. ] 
  <br><br>
  <a href="https://www.linkedin.com/in/m-branum-stephan-84b26aa0/">View My LinkedIn Profile</a> 
  <br>
  <a href = "mailto:branum.stephan@gmail.com">branum.stephan@gmail.com</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
